[package]
name = "scafra-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Procedural macros for the Scafra web framework"

[lib]
proc-macro = true

[dependencies]
scafra-foundation.workspace = true
scafra-build.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
trybuild = "1"
