[package]
name = "ember"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Batteries-included web application framework for Rust"

[dependencies]
axum.workspace = true
ember-config.workspace = true
ember-core.workspace = true
ember-foundation.workspace = true
ember-macros.workspace = true
ember-actuator.workspace = true
ember-scheduler.workspace = true
ember-security.workspace = true
ember-web.workspace = true
inventory.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde.workspace = true
tower.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
