//! Build-script support for Ember's convention-based source layout.

use std::{
    env, fs, io,
    path::{Path, PathBuf},
};

mod discovery;
mod extensions;
mod graph;
mod model;
mod parser;
mod renderer;

pub use extensions::{
    run_extensions, BuildContext, BuildExtension, BuildExtensionError, BuildOutput,
    BuildOutputError, BuildPipelineError,
};

#[cfg(test)]
pub(crate) use discovery::sanitize_ident;
pub(crate) use discovery::{collect_files, collect_source_files};
#[cfg(test)]
pub(crate) use graph::graph_order;
pub(crate) use model::ModuleNode;
#[cfg(test)]
pub(crate) use model::{GraphEdge, SourceFile};
pub(crate) use parser::parse_graph;
pub(crate) use renderer::{render_graph, render_node};

const GENERATED_MODULES_PATH: &str = "ember_modules.rs";

/// Discovers Rust files below `source_root` and writes module declarations to
/// `$OUT_DIR/ember_modules.rs`.
pub fn discover(source_root: impl AsRef<Path>) -> io::Result<()> {
    let context = current_build_context(source_root)?;
    let generated = render_modules(context.source_root())?;
    fs::write(context.output_dir().join(GENERATED_MODULES_PATH), generated)
}

/// Discovers source modules and emits an opt-in, typed application graph.
pub fn discover_graph(source_root: impl AsRef<Path>) -> io::Result<()> {
    let context = current_build_context(source_root)?;
    let generated = render_graph_source(context.source_root(), context.manifest_dir())?;
    fs::write(context.output_dir().join(GENERATED_MODULES_PATH), generated)
}

/// Discovers source modules, stages the generated module artifact, and runs
/// explicit build-time extensions before committing all artifacts.
pub fn discover_with_extensions(
    source_root: impl AsRef<Path>,
    extensions: Vec<Box<dyn BuildExtension>>,
) -> Result<(), BuildPipelineError> {
    let context = current_build_context(source_root).map_err(discovery_failure)?;
    let generated = render_modules(context.source_root()).map_err(discovery_failure)?;
    run_discovery_extensions(context, generated, extensions)
}

/// Discovers source modules and the typed graph, then runs explicit build-time
/// extensions before committing all artifacts.
pub fn discover_graph_with_extensions(
    source_root: impl AsRef<Path>,
    extensions: Vec<Box<dyn BuildExtension>>,
) -> Result<(), BuildPipelineError> {
    let context = current_build_context(source_root).map_err(discovery_failure)?;
    let generated = render_graph_source(context.source_root(), context.manifest_dir())
        .map_err(discovery_failure)?;
    run_discovery_extensions(context, generated, extensions)
}

fn current_build_context(source_root: impl AsRef<Path>) -> io::Result<BuildContext> {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").ok_or_else(|| {
            io::Error::new(io::ErrorKind::NotFound, "CARGO_MANIFEST_DIR is not set")
        })?);
    let out_dir = PathBuf::from(
        env::var_os("OUT_DIR")
            .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "OUT_DIR is not set"))?,
    );
    let source_root = manifest_dir.join(source_root.as_ref());
    println!("cargo:rerun-if-changed={}", source_root.display());
    Ok(BuildContext::new(manifest_dir, source_root, out_dir))
}

fn render_modules(source_root: &Path) -> io::Result<String> {
    let mut root = ModuleNode::default();
    collect_files(source_root, &mut Vec::new(), &mut root)?;

    let mut generated = String::from("// @generated by ember-build; do not edit.\n");
    render_node(&root, 0, &mut generated);
    Ok(generated)
}

fn render_graph_source(source_root: &Path, manifest_dir: &Path) -> io::Result<String> {
    let mut root = ModuleNode::default();
    collect_files(source_root, &mut Vec::new(), &mut root)?;
    let mut files = Vec::new();
    collect_source_files(source_root, &mut Vec::new(), manifest_dir, &mut files)?;
    let graph = parse_graph(&files)?;

    let mut generated = String::from("// @generated by ember-build; do not edit.\n");
    render_node(&root, 0, &mut generated);
    match graph {
        Ok(model) => render_graph(&model, &mut generated),
        Err(errors) => {
            for error in errors {
                generated.push_str("compile_error!(");
                generated.push_str(&format!("{:?}", error));
                generated.push_str(");\n");
            }
        }
    }
    Ok(generated)
}

fn run_discovery_extensions(
    context: BuildContext,
    generated: String,
    extensions: Vec<Box<dyn BuildExtension>>,
) -> Result<(), BuildPipelineError> {
    let mut output = BuildOutput::new();
    output
        .emit(GENERATED_MODULES_PATH, generated)
        .map_err(|error| BuildPipelineError::OutputFailure {
            metadata: None,
            error,
        })?;
    run_extensions(extensions, &context, &mut output)?;
    output
        .commit(context.output_dir())
        .map_err(|(path, source)| BuildPipelineError::CommitFailure { path, source })
}

fn discovery_failure(source: io::Error) -> BuildPipelineError {
    BuildPipelineError::DiscoveryFailure { source }
}

#[cfg(test)]
mod tests;
